version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter -v build apk
      - slack/status:
          success_message: ':tada: $CIRCLE_BRANCH のデプロイが完了しました\n:octocat: User : $CIRCLE_USERNAME'
          failure_message: ':red_circle: $CIRCLE_BRANCH のデプロイが失敗しました\n:octocat: User : $CIRCLE_USERNAME'
          webhook: "${SLACK_WEBHOOK}"

workflows:
  version: 2
  flutter:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/